# Generated by Django 4.2.6 on 2026-01-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrestaurant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saveddeal",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="restaurants.deal",
            ),
        ),
        migrations.AddField(
            model_name="saveddeal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_profile",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="restaurantimage",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="restaurants",
                to="restaurants.restaurantcategory",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="restaurants.city",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisines",
            field=models.ManyToManyField(
                blank=True, related_name="restaurants", to="restaurants.cuisine"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="vouchers.merchant",
            ),
        ),
        migrations.AddField(
            model_name="openingslot",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_slots",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="restaurants.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="menucategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_uses",
                to="restaurants.deal",
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_uses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealimage",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="restaurants.deal",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="cuisine",
            index=models.Index(
                fields=["is_active", "name"], name="restaurants_is_acti_9f7f19_idx"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="restaurants.country",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="savedrestaurant",
            index=models.Index(
                fields=["user", "created_at"], name="restaurants_user_id_176350_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedrestaurant",
            unique_together={("user", "restaurant")},
        ),
        migrations.AddIndex(
            model_name="saveddeal",
            index=models.Index(
                fields=["user", "created_at"], name="restaurants_user_id_9ca5a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saveddeal",
            unique_together={("user", "deal")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["restaurant", "rating"], name="restaurants_restaur_b15b99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "created_at"], name="restaurants_user_id_5f7ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["restaurant", "created_at"],
                name="restaurants_restaur_9b1a7f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "restaurant")},
        ),
        migrations.AddIndex(
            model_name="restaurantprofile",
            index=models.Index(
                fields=["user", "restaurant"], name="restaurants_user_id_38455c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "verified"], name="restaurants_city_id_a18ffc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_featured", "verified"],
                name="restaurants_is_feat_da52ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["latitude", "longitude"], name="restaurants_latitud_bcb1fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="openingslot",
            index=models.Index(
                fields=["restaurant", "day_of_week"],
                name="restaurants_restaur_384b56_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="openingslot",
            unique_together={("restaurant", "day_of_week")},
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_available"],
                name="restaurants_categor_33aa85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["restaurant", "is_active", "order"],
                name="restaurants_restaur_d3f244_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("restaurant", "name")},
        ),
        migrations.AddIndex(
            model_name="dealuse",
            index=models.Index(
                fields=["user", "deal"], name="restaurants_user_id_9d4691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealuse",
            index=models.Index(
                fields=["used_at"], name="restaurants_used_at_5d58d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["restaurant", "is_active"],
                name="restaurants_restaur_264ad2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["start_date", "end_date", "is_active"],
                name="restaurants_start_d_eefc6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="restaurants_is_feat_602923_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["is_active", "country"], name="restaurants_is_acti_9c4b68_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "booking_date"], name="restaurants_user_id_7af16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["restaurant", "booking_date"],
                name="restaurants_restaur_d64613_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "booking_date"], name="restaurants_status_ab47ab_idx"
            ),
        ),
    ]
