# Generated by Django 4.2.27 on 2026-01-17 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saveddeal',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='restaurants.deal'),
        ),
        migrations.AddField(
            model_name='saveddeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.restaurantcategory'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.city'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='vouchers.merchant'),
        ),
        migrations.AddField(
            model_name='dealuse',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_uses', to='restaurants.deal'),
        ),
        migrations.AddField(
            model_name='dealuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_uses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.deal'),
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='restaurants.country'),
        ),
        migrations.AddIndex(
            model_name='savedrestaurant',
            index=models.Index(fields=['user', 'created_at'], name='restaurants_user_id_176350_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedrestaurant',
            unique_together={('user', 'restaurant')},
        ),
        migrations.AddIndex(
            model_name='saveddeal',
            index=models.Index(fields=['user', 'created_at'], name='restaurants_user_id_9ca5a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddeal',
            unique_together={('user', 'deal')},
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'verified'], name='restaurants_city_id_a18ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_featured', 'verified'], name='restaurants_is_feat_da52ba_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='restaurants_latitud_bcb1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='dealuse',
            index=models.Index(fields=['user', 'deal'], name='restaurants_user_id_9d4691_idx'),
        ),
        migrations.AddIndex(
            model_name='dealuse',
            index=models.Index(fields=['used_at'], name='restaurants_used_at_5d58d1_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurants_restaur_264ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date', 'end_date', 'is_active'], name='restaurants_start_d_eefc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_featured', 'is_active'], name='restaurants_is_feat_602923_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active', 'country'], name='restaurants_is_acti_9c4b68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
