# Generated by Django 5.2.10 on 2026-02-05 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealuse",
            name="is_redeemed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this redemption has been completed in the restaurant",
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image encoding the redemption reference",
                null=True,
                upload_to="deal_redemptions/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="redeemed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="redeemed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant staff user who performed the redemption",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_deal_uses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="redemption_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique 6-digit numeric code used for in-restaurant redemption",
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dealuse",
            index=models.Index(
                fields=["redemption_code"], name="restaurants_redempt_0e4bf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dealuse",
            index=models.Index(
                fields=["is_redeemed", "redeemed_at"],
                name="restaurants_is_rede_34e522_idx",
            ),
        ),
    ]
