# Generated by Django 5.2.10 on 2026-02-26 05:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_dealuse_is_redeemed_dealuse_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='occupancy',
            field=models.CharField(choices=[('available', 'Available'), ('moderately_busy', 'Moderately Busy'), ('very_busy', 'Very Busy')], default='available', help_text='Current occupancy status as shown to users.', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='required_visit_gap',
            field=models.PositiveIntegerField(default=30, help_text='Required minimum gap in days between scheduled mystery visits.'),
        ),
        migrations.CreateModel(
            name='MysteryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(help_text='Planned date/time for the visit.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final weighted mystery score (0–100).', max_digits=5, null=True)),
                ('is_risk_flagged', models.BooleanField(default=False, help_text='Flag for restaurants requiring quality follow-up.')),
                ('comments', models.TextField(blank=True)),
                ('mystery_guest', models.ForeignKey(help_text='Mystery Guest assigned to perform this visit.', on_delete=django.db.models.deletion.CASCADE, related_name='mystery_visits', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_visits', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MysteryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('pre_visit', 'Pre-Visit'), ('ambience', 'Ambience'), ('service', 'Service'), ('food', 'Food'), ('discount_experience', 'Discount Experience'), ('hygiene', 'Hygiene')], db_index=True, max_length=50)),
                ('score', models.PositiveIntegerField(help_text='Section score on a 0–10 scale.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='restaurants.mysteryvisit')),
            ],
        ),
        migrations.CreateModel(
            name='MysteryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='mystery_evidence/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='restaurants.mysteryvisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='mysteryvisit',
            index=models.Index(fields=['restaurant', 'scheduled_for'], name='restaurants_restaur_160864_idx'),
        ),
        migrations.AddIndex(
            model_name='mysteryvisit',
            index=models.Index(fields=['mystery_guest', 'scheduled_for'], name='restaurants_mystery_727cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='mysteryvisit',
            index=models.Index(fields=['status', 'scheduled_for'], name='restaurants_status_f9a197_idx'),
        ),
        migrations.AddIndex(
            model_name='mysteryscore',
            index=models.Index(fields=['visit', 'section'], name='restaurants_visit_i_60f061_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mysteryscore',
            unique_together={('visit', 'section')},
        ),
        migrations.AddIndex(
            model_name='mysteryevidence',
            index=models.Index(fields=['visit', 'created_at'], name='restaurants_visit_i_832b45_idx'),
        ),
    ]
