# Generated by Django 5.2.10 on 2026-03-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0004_restaurant_occupancy_restaurant_required_visit_gap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dealuse",
            name="people_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
