# Generated by Django 5.2.10 on 2026-03-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_facility_restaurant_facilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menu_type",
            field=models.CharField(
                choices=[("structured", "Structured Menu"), ("image", "Image Menu")],
                default="structured",
                help_text="Whether to show structured menu items or uploaded menu images.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="restaurantimage",
            name="image_type",
            field=models.CharField(
                choices=[("gallery", "Gallery"), ("menu", "Menu Image")],
                default="gallery",
                max_length=20,
            ),
        ),
    ]
