# Generated by Django 5.2.10 on 2026-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_restaurant_menu_type_restaurantimage_image_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealuse",
            name="discount_amount_saved",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dealuse",
            name="final_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
