# Generated by Django 5.2.10 on 2026-03-30 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_dealuse_discount_amount_saved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Restaurant Partner Request',
                'verbose_name_plural': 'Restaurant Partner Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
