# Generated by Django 5.2.10 on 2026-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantpartnerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpartnerrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
