# Generated by Django 5.2.10 on 2026-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_alter_restaurantpartnerrequest_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="combo_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price for the combo",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_type",
            field=models.CharField(
                choices=[
                    ("two_for_one", "2-for-1"),
                    ("percentage", "Percentage Discount"),
                    ("fixed", "Fixed Discount"),
                    ("combo", "Combo Deal"),
                    ("other", "Other"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
    ]
