# Generated by Django 5.2.10 on 2026-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_deal_combo_price_alter_deal_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Two-word description (e.g. Save Today)",
                max_length=50,
                null=True,
            ),
        ),
    ]
