# Generated by Django 5.2.10 on 2026-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0013_alter_city_latitude_alter_city_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="arrived_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="no_show_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="no_show_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("arrived", "Arrived"),
                    ("no_show", "No Show"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
