# Generated by Django 5.2.10 on 2026-06-22 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0014_booking_arrived_time_booking_no_show_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="loyalty_card_enabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this restaurant runs a loyalty card program.",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="loyalty_required_redemptions",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of successful redemptions required to earn a reward.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="loyalty_reward_description",
            field=models.TextField(
                blank=True,
                help_text="Description of the reward granted when required redemptions are reached.",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyRedemptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("counted", "Counted toward loyalty"),
                            ("reward_earned", "Reward eligibility reached"),
                            ("reward_claimed", "Reward claimed"),
                        ],
                        default="counted",
                        max_length=20,
                    ),
                ),
                (
                    "cycle_redemption_number",
                    models.PositiveIntegerField(
                        help_text="Redemption number within the current loyalty cycle after this event."
                    ),
                ),
                (
                    "total_lifetime_redemptions",
                    models.PositiveIntegerField(
                        help_text="Total lifetime redemptions at this restaurant after this event."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "deal_use",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_records",
                        to="restaurants.dealuse",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_redemption_records",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_redemption_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "user", "-created_at"],
                        name="restaurants_restaur_dcd96f_idx",
                    ),
                    models.Index(
                        fields=["deal_use"], name="restaurants_deal_us_c816e4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRestaurantLoyalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_cycle_redemptions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Redemptions counted toward the next reward in the current cycle.",
                    ),
                ),
                (
                    "total_lifetime_redemptions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total successful redemptions at this restaurant (all time).",
                    ),
                ),
                (
                    "rewards_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of loyalty rewards earned (claimed).",
                    ),
                ),
                (
                    "is_reward_eligible",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the user has reached the required redemption count and can claim a reward.",
                    ),
                ),
                ("reward_eligible_at", models.DateTimeField(blank=True, null=True)),
                ("last_reward_claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_loyalties",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_loyalties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User restaurant loyalties",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "is_reward_eligible"],
                        name="restaurants_restaur_4c6efd_idx",
                    ),
                    models.Index(
                        fields=["user", "restaurant"],
                        name="restaurants_user_id_c06005_idx",
                    ),
                ],
                "unique_together": {("user", "restaurant")},
            },
        ),
    ]
