# Generated by Django 5.2.10 on 2026-07-02 11:44

import core.utils.image_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_loyalty_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_large_upload_to),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_medium_upload_to),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='image_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='image_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='dealimage',
            name='original',
            field=models.ImageField(blank=True, help_text='Unmodified upload retained for reprocessing and fallback.', null=True, upload_to=core.utils.image_paths.processed_original_upload_to),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_large_upload_to),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_medium_upload_to),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='original',
            field=models.ImageField(blank=True, help_text='Unmodified upload retained for reprocessing and fallback.', null=True, upload_to=core.utils.image_paths.processed_original_upload_to),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_large_upload_to),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_medium_upload_to),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_thumb_upload_to),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='original',
            field=models.ImageField(blank=True, help_text='Unmodified upload retained for reprocessing and fallback.', null=True, upload_to=core.utils.image_paths.processed_original_upload_to),
        ),
    ]
