# Generated by Django 5.2.10 on 2026-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_processed_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealimage',
            name='image_processing_error',
        ),
        migrations.RemoveField(
            model_name='dealimage',
            name='image_processing_status',
        ),
        migrations.RemoveField(
            model_name='dealimage',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='dealimage',
            name='original',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_processing_error',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_processing_status',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='original',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='image_processing_error',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='image_processing_status',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='original',
        ),
        migrations.AlterField(
            model_name='dealimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/%Y/%m/%d/'),
        ),
    ]
