# Generated by Django 5.2.10 on 2026-07-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_streamline_image_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealuse',
            name='is_loyalty_only',
            field=models.BooleanField(default=False, help_text='True if this is a loyalty-only visit (no deal attached)'),
        ),
        migrations.AddField(
            model_name='dealuse',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Required if deal is null (loyalty-only visit)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_uses', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='userrestaurantloyalty',
            name='reward_code',
            field=models.CharField(blank=True, help_text='6-digit code for claiming the loyalty reward', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userrestaurantloyalty',
            name='reward_qr_code',
            field=models.ImageField(blank=True, help_text='QR code for claiming the loyalty reward', null=True, upload_to='reward_qr_codes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dealuse',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_uses', to='restaurants.deal'),
        ),
    ]
