# Generated by Django 5.2.10 on 2026-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_alter_city_latitude_alter_city_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bookings_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this restaurant accepts bookings.'),
        ),
    ]
