# Generated by Django 5.2.10 on 2026-08-14 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_restaurant_bookings_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('view', 'Deal View'), ('click', 'Deal Click / Claim')], db_index=True, default='click', max_length=20)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='restaurants.deal')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_click_logs', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_click_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', 'action_type', 'created_at'], name='restaurants_deal_id_7a0383_idx'), models.Index(fields=['restaurant', 'created_at'], name='restaurants_restaur_76c93e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_type', models.CharField(choices=[('detail', 'Detail View'), ('map', 'Map Visibility Impression'), ('list', 'List View Impression')], db_index=True, default='detail', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'view_type', 'created_at'], name='restaurants_restaur_85e6d4_idx'), models.Index(fields=['restaurant', 'created_at'], name='restaurants_restaur_891afe_idx')],
            },
        ),
    ]
