# Generated by Django 5.2.10 on 2026-09-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_dealclicklog_restaurantviewlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openingslot',
            unique_together=set(),
        ),
    ]
