# Generated by Django 5.2.10 on 2026-02-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationotp',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('mystery_guest', 'Mystery Guest')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('mystery_guest', 'Mystery Guest')], default='customer', max_length=20),
        ),
    ]
