# Generated by Django 5.2.10 on 2026-07-02 11:44

import core.utils.image_paths
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_large',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_large_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_medium',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_medium_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_original',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_original_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_thumb_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_source_upload_to),
        ),
    ]
