# Generated by Django 5.2.10 on 2026-07-02 12:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_processed_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_original',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_processing_error',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_processing_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_thumb',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload intake only; cleared after WebP processing.', null=True, upload_to=users.models.profile_picture_source_upload_to),
        ),
    ]
