# Generated by Django 5.2.10 on 2026-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first/have higher priority'),
        ),
    ]
