# Generated by Django 5.2.10 on 2026-07-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processed_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_processing_error',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_processing_status',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='original',
        ),
    ]
