# Generated by Django 5.2.10 on 2026-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_streamline_image_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_url',
            field=models.CharField(blank=True, default='', help_text='Tap target: in-app route (e.g. /restaurants/slug) or https URL.', max_length=500),
        ),
    ]
