# Generated by Django 5.2.10 on 2026-08-14 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback')),
                ('target_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('deal', 'Deal'), ('spin_to_win', 'Spin to Win'), ('external_url', 'External URL'), ('none', 'None')], default='none', max_length=50)),
                ('target_value', models.CharField(blank=True, help_text='Slug, ID, or external link', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinToWinCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Spin & Win Rewards', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_spins_per_user_per_day', models.PositiveIntegerField(default=1)),
                ('total_spins_count', models.PositiveIntegerField(default=0, help_text='Total spins count conducted across all users')),
            ],
            options={
                'db_table': 'spin_to_win_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinToWinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spin_items/%Y/%m/%d/')),
                ('item_type', models.CharField(choices=[('promocode', 'Promo Code'), ('discount', 'Discount'), ('empty', 'Try Again'), ('points', 'Reward Points')], default='promocode', max_length=30)),
                ('promo_code_value', models.TextField(blank=True, help_text="Text message / Promo code text awarded for this item (e.g. 'Use code SAVE50 at checkout')")),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_spins_before_win', models.PositiveIntegerField(default=0, help_text='Minimum total campaign spins required before giving away this item')),
                ('stock_limit', models.PositiveIntegerField(blank=True, help_text='Max times this prize can be given away across all users. Null = unlimited', null=True)),
                ('times_won', models.PositiveIntegerField(default=0)),
                ('probability_weight', models.PositiveIntegerField(default=1, help_text='Relative selection weight')),
                ('slice_index', models.PositiveIntegerField(default=0, help_text='Wheel position index')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configs.spintowincampaign')),
            ],
            options={
                'db_table': 'spin_to_win_items',
                'ordering': ['slice_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_win', models.BooleanField(default=False)),
                ('promo_code', models.TextField(blank=True, help_text='Promo code / text message received by the user')),
                ('spun_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_spin_results', to='configs.spintowincampaign')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_records', to='configs.spintowinitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_spin_results',
                'ordering': ['-spun_at'],
            },
        ),
    ]
