# Generated by Django 5.2.10 on 2026-08-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_appbanner_spintowincampaign_spintowinitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppBanner',
        ),
    ]
