# Generated by Django 4.2.6 on 2026-01-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                ("verified", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name_plural": "Voucher categories",
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("discount_percent", models.FloatField()),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("total_quantity", models.PositiveIntegerField()),
                ("sold_quantity", models.PositiveIntegerField(default=0)),
                ("max_per_user", models.PositiveIntegerField(default=5)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vouchers",
                        to="vouchers.vouchercategory",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="vouchers.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "redeemed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_successful", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "voucher"],
                        name="vouchers_vo_user_id_6e6b9c_idx",
                    ),
                    models.Index(
                        fields=["redeemed_at"], name="vouchers_vo_redeeme_d730e9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["code"], name="vouchers_vo_code_7a7b6a_idx"),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["start_date", "end_date"], name="vouchers_vo_start_d_ab7daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["merchant", "category"], name="vouchers_vo_merchan_2c1f6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["verified"], name="vouchers_me_verifie_5f5adf_idx"
            ),
        ),
    ]
