# Generated by Django 5.2.10 on 2026-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('FAV_DEAL', 'Favorite Restaurant Deal'), ('DEAL_REDEEMED', 'Deal Redeemed'), ('SYSTEM', 'System'), ('NEW_BOOKING', 'New Booking Request'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('MERCHANT_DEAL_REDEEMED', 'Deal Redeemed at Your Restaurant'), ('MILESTONE_EARNINGS', 'Earnings Milestone Reached'), ('NEW_REVIEW', 'New Customer Review')], max_length=50),
        ),
    ]
