# Generated by Django 5.2.10 on 2026-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_devicetoken_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("BOOKING_CONFIRMED", "Booking Confirmed"),
                    ("FAV_DEAL", "Favorite Restaurant Deal"),
                    ("DEAL_REDEEMED", "Deal Redeemed"),
                    ("SYSTEM", "System"),
                    ("NEW_BOOKING", "New Booking Request"),
                    ("BOOKING_CANCELLED", "Booking Cancelled"),
                    ("MERCHANT_DEAL_REDEEMED", "Deal Redeemed at Your Restaurant"),
                    ("MILESTONE_EARNINGS", "Earnings Milestone Reached"),
                    ("NEW_REVIEW", "New Customer Review"),
                    ("BOOKING_REMINDER", "Upcoming Booking Reminder"),
                ],
                max_length=50,
            ),
        ),
    ]
