# Generated by Django 5.2.10 on 2026-09-24 05:59

import core.mixins.processed_image
import core.utils.image_paths
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
        ('restaurants', '0022_opening_slot_allow_multiple_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('FAV_DEAL', 'Favorite Restaurant Deal'), ('DEAL_REDEEMED', 'Deal Redeemed'), ('SYSTEM', 'System'), ('NEW_BOOKING', 'New Booking Request'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('MERCHANT_DEAL_REDEEMED', 'Deal Redeemed at Your Restaurant'), ('MILESTONE_EARNINGS', 'Earnings Milestone Reached'), ('NEW_REVIEW', 'New Customer Review'), ('BOOKING_REMINDER', 'Upcoming Booking Reminder'), ('PROMO', 'Admin Promotion')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdminNotificationCampaign',
            fields=[
                ('image_medium', models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_medium_upload_to)),
                ('image_large', models.ImageField(blank=True, null=True, upload_to=core.utils.image_paths.processed_large_upload_to)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification_campaigns/%Y/%m/%d/')),
                ('audience', models.CharField(choices=[('all_customers', 'All customers'), ('restaurant_favourites', 'Restaurant favourites')], default='all_customers', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notification_campaigns', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notification_campaigns', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'admin_notification_campaigns',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.processed_image.ProcessedImageBehaviorMixin, models.Model),
        ),
    ]
