# Generated by Django 5.2.10 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_admin_notification_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationcampaign',
            name='fcm_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adminnotificationcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotificationcampaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('scheduled', 'Scheduled'),
                    ('sending', 'Sending'),
                    ('sent', 'Sent'),
                    ('failed', 'Failed'),
                ],
                db_index=True,
                default='queued',
                max_length=20,
            ),
        ),
    ]
